### ISSUE TITLE
Various clarifications

### ISSUE THREAD

**Issue by kevin-brodsky-arm** [CTSRD-CHERI/morello-early-performance-results#6]
First, thank you for putting this report together, it was a good read and overall very clear. Some bits confused me though:

* Section 3.1: in "SPECint does not have external software dependencies beyond the system library", what is the "system library" exactly, is that libc? The plural "system libraries" would not have surprised me, but the singular does.
* Section 3.3: I struggle to understand what "capability jump register" means exactly. I expect something like "capability-based jump"?
* Section 4.2: typo "bypas ing"
* Section 4.3: in the graph, I understand that the dashed lines correspond to the geomean overhead, but what do the bars represent?

**Comment by rwatson** [comment]
The above commit addresses all of these (I hope) but the query about 4.3. Here, the bars represent the specific overheads of individual benchmarks. We likely should describe the graphs more specifically in the body text.

**Comment by kevin-brodsky-arm** [comment]
Thanks, the fix looks good. About 4.3, I see it now, it was in fact fairly obvious! I somehow didn't realise that the geomean lines spanned all the benchmarks - i.e. it is the average of all benchmarks.
